---
sidebar: sidebar 
permalink: oci/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials, oci nss, oracle cloud infrastructure 
summary: 'Añade las credenciales de Oracle Cloud Infrastructure (OCI) para que Workload Factory disponga de los permisos que necesita para implementar y gestionar recursos en la nube en tus cuentas de OCI.' 
---
= Agregar credenciales de Oracle Cloud Infrastructure a NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Añade y gestiona las credenciales de tu proveedor de servicios en la nube para que NetApp Workload Factory disponga de los permisos necesarios para implementar y gestionar recursos en tus cuentas de dicho proveedor.

link:permissions-oci.html["Permisos para OCI NetApp Storage Service"]

.Acerca de esta tarea
Puedes añadir credenciales a una cuenta existente de Workload Factory desde la página Credentials. Esto proporciona a Workload Factory los permisos necesarios para gestionar recursos y procesos dentro de tu entorno en la nube.

.Antes de empezar
Necesitarás unas credenciales para iniciar sesión en tu cuenta de Oracle Cloud Infrastructure.

.Pasos
. Inicia sesión en el https://console.netapp.com/["NetApp Console"^].
. En el menú, selecciona *Cargas de trabajo* > *Administración* > *Credenciales*.
. En la página Credenciales, selecciona *Add credentials*.
. En la página Add Oracle Cloud Infrastructure NetApp Storage Service credentials, haz lo siguiente:
+
.. En «Configuración de permisos», selecciona los permisos adecuados para las credenciales del servicio de almacenamiento «NetApp» de Oracle Cloud Infrastructure. Los permisos «Ver, planificar y analizar» son los predeterminados. Esta política de permisos te permite ver los grupos de almacenamiento de OCI NSS, conocer el estado del sistema, obtener el análisis well-architected de tus sistemas y explorar oportunidades de ahorro.
.. Sigue los pasos manuales proporcionados mediante Oracle Cloud Console para completar la configuración de permisos de las credenciales de OCI NSS.
.. En _Nombre de las credenciales_, introduce el nombre que quieras usar para estas credenciales e introduce el OCID de la tenencia.


. Selecciona *Add*.


.Qué sigue
link:quick-start-oci.html["Guía de inicio rápido para Oracle Cloud Infrastructure NetApp Storage Service en NetApp Workload Factory."]
