---
sidebar: sidebar 
permalink: fsx-storage/learn-fsx-ontap.html 
keywords: Amazon FSx for NetApp ONTAP, FSx, storage, aws 
summary: Amazon FSx for NetApp ONTAP es un servicio totalmente gestionado que permite a los clientes iniciar y ejecutar sistemas de archivos como backend de almacenamiento para sus cargas de trabajo dentro de Workload Factory. 
---
= Descubre Amazon FSx for NetApp ONTAP en NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Amazon FSx for NetApp ONTAP es un servicio de almacenamiento de datos totalmente gestionado y de datos basados en cloud que proporciona capacidades avanzadas de gestión de datos y un rendimiento altamente escalable. FSx for ONTAP te permite crear y gestionar sistemas de archivos como el backend de almacenamiento para todas tus cargas de trabajo dentro de NetApp Workload Factory.

FSx for ONTAP ofrece las mismas funciones, el mismo rendimiento y las mismas capacidades de administración que los clientes de NetApp usan actualmente en sus instalaciones, con la simplicidad, la agilidad, la seguridad y la escalabilidad de un servicio nativo de AWS.

FSx for ONTAP es el componente _Storage_ de Workload Factory.



[[features]]
== Funciones

FSx for ONTAP ofrece las siguientes funciones:

* *Servicio totalmente gestionado*: ofrece un servicio totalmente gestionado integrado con la consola de Workload Factory.
* *Alta disponibilidad*: ofrece alta disponibilidad para cada sistema de archivos FSx for ONTAP y admite implementaciones en Single y Multiple Availability Zones.
* *Instantáneas automatizadas*: protege los datos con instantáneas automatizadas y eficientes, que son copias de solo lectura del sistema de archivos o de los volúmenes en un momento específico, casi instantáneas y con uso eficiente del espacio.
* *Replicación de volúmenes*: ofrece recuperación ante desastres mediante la replicación entre regiones en Amazon Web Services.
* *Copias de seguridad eficientes*: añade una capa adicional de protección mediante una copia de los datos en otra región para casos de emergencia.
* *Clonación rápida*: acelera el desarrollo de aplicaciones gracias a la clonación rápida.
* *Compatibilidad con múltiples protocolos*: es compatible con los protocolos NFS (Network File System), SMB (Server Message Block) e iSCSI (Internet Small Computer Systems Interface).
* *Alto rendimiento*: ofrece un alto rendimiento para garantizar latencias bajas en las cargas de trabajo que se ejecutan sobre los sistemas de archivos FSx for ONTAP.
* *Caché en memoria y caché NVMe*: incluye una caché en memoria y una caché NVMe únicas, que potencian el rendimiento de los datos a los que se accede con frecuencia.
* *Cientos de miles de IOPS*: ofrece cientos de miles de IOPS con discos SSD, lo que garantiza que tu almacenamiento y tus cargas de trabajo obtengan resultados en el momento oportuno.
* *Thin Provisioning*: permite aprovisionar capacidad por adelantado, lo que supone un ahorro de costes hasta que se necesite más capacidad.
* *Deduplicación y compresión de datos*: elimina los datos duplicados y comprime los datos para reducir la cantidad de almacenamiento físico necesaria para los sistemas de archivos FSx for ONTAP, lo que se traduce en un ahorro de costes.
* *Clasificación por niveles de datos*: permite reducir los costes de almacenamiento moviendo los datos a los que se accede con menos frecuencia del nivel de almacenamiento SSD principal, de alto rendimiento, al nivel de almacenamiento secundario del pool de capacidad.




[[additional-features-in-workload-factory]]
== Funciones adicionales en Workload Factory

* *Calculadora de comparación de costes de almacenamiento*: compara los costes de almacenamiento de Amazon Elastic Block Store (EBS), Elastic File System (EFS) y FSx for Windows File Server con los de FSx for ONTAP. Desde la calculadora, puedes ver cómo las configuraciones de almacenamiento de FSx for ONTAP ofrecen un ahorro potencial y planificar tu migración al almacenamiento de FSx for ONTAP.
* *interfaz de usuario de Workload Factory*: ofrece las opciones de modo de implementación _Creación rápida_ y _Creación avanzada_. La opción «Creación rápida» incluye AWS, NetApp y las mejores prácticas estándar del sector para tus configuraciones de almacenamiento.
* *Codebox*: ofrece a los desarrolladores un visor de código para las operaciones de FSx for ONTAP, plantillas de código para copiar y descargar, y un catálogo de automatización para reutilizar código.




[[tools-to-use-netapp-workload-factory]]
== Herramientas para usar NetApp Workload Factory

Puedes utilizar NetApp Workload Factory con las siguientes herramientas:

* *Workload Factory console*: Workload Factory console te ofrece una vista visual e integral de tus aplicaciones y proyectos.
* *NetApp Console*: la NetApp Console ofrece una experiencia de interfaz híbrida para que puedas usar Workload Factory junto con otros servicios de datos de NetApp.
* *Ask me*: usa el asistente de IA Ask me para hacer preguntas y obtener más información sobre Workload Factory sin salir de la consola de Workload Factory. Accede a Ask me desde el menú de ayuda de Workload Factory.
* *CloudShell CLI*: Workload Factory incluye una CLI de CloudShell para gestionar y operar entornos de AWS y NetApp entre cuentas desde una única CLI basada en navegador. Accede a CloudShell desde la barra superior de la consola de Workload Factory.
* *API de REST*: Utiliza las API de REST de Workload Factory para implementar y gestionar tus sistemas de archivos FSx for ONTAP y otros recursos de AWS.
* *CloudFormation*: utiliza el código de AWS CloudFormation para llevar a cabo las acciones que hayas definido en la consola de Workload Factory con el fin de modelar, aprovisionar y gestionar recursos de AWS y de terceros desde la pila de CloudFormation en tu cuenta de AWS.
* *NetApp Terraform provider*: utiliza Terraform para crear y gestionar los flujos de trabajo de infraestructura generados en la consola de Workload Factory.




[[cost]]
== Coste

AWS mantiene tu cuenta de FSx for ONTAP, no Workload Factory. Consulta link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html#pricing-for-fsx-ontap["Precios de Amazon FSx for NetApp ONTAP"^].



[[regions]]
== Regiones

Workload factory es compatible en todas las regiones comerciales donde se admite FSx for ONTAP. link:https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Consulta las regiones de Amazon compatibles."^]

Las siguientes regiones de AWS no son compatibles:

* Regiones de China
* Secret Cloud
* Top Secret Cloud




[[getting-help]]
== Cómo obtener ayuda

Amazon FSx for NetApp ONTAP es una solución propia de AWS. Si tienes preguntas o necesitas soporte técnico relacionado con tu sistema de archivos FSx for ONTAP, la infraestructura o cualquier solución que utilice este servicio, usa el Support Center de tu AWS Management Console para abrir un caso de soporte técnico con AWS. Selecciona el servicio “FSx for ONTAP” y la categoría adecuada. Proporciona el resto de la información necesaria para crear tu caso de soporte técnico de AWS.

Si tienes preguntas generales sobre Workload Factory o sobre las aplicaciones y servicios de Workload Factory, consulta link:../get-help.html["Obtén ayuda para FSx for ONTAP for Workload Factory"].
