---
sidebar: sidebar 
permalink: gcnv/add-credentials.html 
keywords: permissions, policy, iam, iam role, role, granting, iam policy, iam user, access keys, arn, aws accounts, aws, aws profile, json, credentials, adding credentials, add credentials 
summary: Añade las credenciales de Google Cloud NetApp Volumes para que Workload Factory disponga de los permisos que necesita para implementar y gestionar recursos en la nube en tus cuentas de Google. 
---
= Añade las credenciales de Google Cloud NetApp Volumes a NetApp Workload Factory
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Añade y gestiona las credenciales de tu proveedor de servicios en la nube para que NetApp Workload Factory disponga de los permisos necesarios para implementar y gestionar recursos en tus cuentas de dicho proveedor.



[[overview]]
== Descripción general

Puedes añadir las credenciales de Google Cloud NetApp Volumes desde la página Credentials en NetApp console. La consola ofrece instrucciones de configuración guiadas y un enlace a la documentación para que puedas completar la configuración necesaria de Google Cloud y luego volver para terminar de añadir las credenciales.

Utiliza este flujo de trabajo para conceder a Workload Factory los permisos que necesita para detectar, analizar y gestionar los recursos de tu entorno de Google Cloud.

La creación de las credenciales consta de tres partes:

* Paso 1: selecciona el nivel de permisos que deseas conceder a Workload Factory.
* Paso 2: crea y valida una cuenta de servicio de Google Cloud y, a continuación, selecciona el proyecto de Google Cloud que deseas gestionar.
* Paso 3: introduce un nombre para las credenciales y añádelas.


.Antes de empezar
Necesitarás unas credenciales para iniciar sesión en tu cuenta de Google Cloud.

.Pasos
. Inicia sesión en el https://console.netapp.com/["NetApp Console"^].
. En el menú, selecciona *Cargas de trabajo* > *Administración* > *Credenciales*.
. En la página Credenciales, selecciona *Add credentials*.
. Selecciona *Google Cloud NetApp Volumes* como proveedor de servicios en la nube.
. En la página Add Google Cloud NetApp Volumes credentials, completa cada sección en *Permissions configuration*.




[[step-1-create-permission-policies]]
=== Paso 1: crear políticas de permisos

.Pasos
. En *Crear políticas de permisos*, la opción *Ver, planificar y analizar* está seleccionada de forma predeterminada. Esta política de permisos te permite ver los grupos de almacenamiento de Google Cloud NetApp Volumes, conocer el estado del sistema, obtener el análisis well-architected de tus sistemas y explorar posibilidades de ahorro.
. Opcional: selecciona *operaciones y corrección* si también quieres que Workload Factory gestione los recursos de Google Cloud NetApp Volumes y solucione los problemas de configuración.
. Consulta las instrucciones de configuración en link:https://docs.netapp.com/us-en/storage-management-google-cloud-netapp-volumes/task-set-up-gcnv.html#set-up-a-service-account["Configura Google Cloud NetApp Volumes"^] antes de continuar.




[[step-2-create-the-google-cloud-service-account]]
=== Paso 2: crear la cuenta de servicio de Google Cloud

.Pasos
. Expande *Configurar tu entorno de Google Cloud*.
. Sigue los pasos del 1 al 5 que se muestran en pantalla para crear una cuenta de servicio de Google Cloud.
. Copia la dirección de correo electrónico de la cuenta de servicio.
. Vuelve a Workload Factory, pega la dirección de correo electrónico en el campo *GCP service account* y selecciona *Validate credentials*.
. Una vez completada la validación, en el menú desplegable *Proyectos*, selecciona el proyecto de Google Cloud que quieres que gestione Workload Factory. NOTA: la lista de proyectos no estará disponible hasta que se verifiquen las credenciales de la cuenta de servicio.




[[step-3-enter-the-credentials-name]]
=== Paso 3: introduce el nombre de las credenciales

.Pasos
. Expande *Nombre de las credenciales*.
. En el campo *Nombre*, introduce un nombre para las credenciales utilizando solo caracteres alfanuméricos. No se permiten caracteres especiales ni espacios.
. Selecciona *Add*.


.Resultado
Las credenciales de Google Cloud NetApp Volumes se han añadido a tu cuenta y están disponibles para las operaciones compatibles de Workload Factory.
