---
sidebar: sidebar 
permalink: fsx-vmware/deploy-fsx-file-system.html 
keywords: vm workloads, deploy fsx, deploy storage for vms 
summary: Después de verificar que el sistema de archivos FSx for ONTAP recomendado, o los sistemas de archivos en algunos casos, cumple exactamente con tus requisitos, puedes usar Workload Factory para implementar el sistema en tu entorno de AWS. 
---
= Implementa el sistema de archivos FSx para ONTAP recomendado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una vez que hayas comprobado que el sistema de archivos FSx for ONTAP recomendado (o varios sistemas de archivos en algunos casos) se ajusta exactamente a tus necesidades, puedes utilizar Workload Factory para implementar el sistema en tu entorno de AWS.

En función de la política y los permisos que hayas añadido a tu cuenta de Workload Factory, puedes desplegar por completo el sistema de archivos FSx for ONTAP mediante Workload Factory (usando el modo de lectura/escritura). Si tienes menos permisos (modo de solo lectura), o no tienes permisos (modo Basic), tendrás que usar la información de CloudFormation del Codebox y desplegar tú mismo el sistema de archivos FSx for ONTAP en AWS.

.Requisitos para implementaciones en VMware Cloud on AWS
* Debes utilizar VMware Cloud on AWS Software-Defined Data Center (SDDC) versión 1.20 o superior para implementar sistemas de archivos FSx for ONTAP.
* No debes implementar el sistema de archivos FSx for ONTAP en la misma VPC utilizada durante la implementación del SDDC. En su lugar, debes implementarlo en una nueva Amazon VPC de tu propiedad para habilitar la integración de VMware Cloud on AWS con Amazon FSx for NetApp ONTAP.
* Debes implementar el sistema de archivos FSx for ONTAP en la misma región de AWS que tu SDDC.


.Pasos
. En la parte inferior de la página *Revisar plan*, selecciona *Implementar* y se muestra la página Crear un sistema de archivos FSx for ONTAP.
+
La mayoría de los campos que definen tu sistema de archivos FSx for ONTAP se han completado en función de la información que proporcionaste, pero hay algunos campos que debes completar en esta página.

+
Puedes usar la opción Quick create o Advanced create. Advanced create ofrece algunos parámetros de almacenamiento adicionales que puedes personalizar. link:../fsx-storage/create-discover-systems.html["Descubre qué te ofrecen estas dos opciones"].

. *Credenciales de AWS*: selecciona o añade las credenciales que otorgarán a Workload Factory los permisos necesarios para crear directamente tu sistema de archivos FSx for ONTAP. También puedes seleccionar el código CloudFormation de Codebox e implementar tú mismo el sistema de archivos FSx for ONTAP en AWS.
. *Nombre del sistema de archivos*: introduce el nombre que deseas utilizar para este sistema de archivos FSx for ONTAP.
. *Etiquetas*: si lo deseas, puedes añadir etiquetas para clasificar este sistema de archivos FSx for ONTAP.
. En la sección «Red y seguridad», introduce la siguiente información:
+
.. *Región y VPC*: selecciona la región y la VPC donde se implementará el sistema de archivos FSx for ONTAP.
+
Si vas a realizar la implementación en VMware Cloud on AWS, asegúrate de hacerlo en una VPC distinta de aquella en la que está implementado VMware Cloud on AWS.

.. *Grupo de seguridad*: al utilizar la opción *Advanced create*, puedes seleccionar el grupo de seguridad predeterminado para la VPC de FSx for ONTAP, de modo que todo el tráfico pueda acceder al sistema de archivos de FSx for ONTAP.
+
Puedes añadir una regla de entrada que restrinja a qué otros servicios de AWS se puede acceder en el sistema de archivos FSx for ONTAP. Esto reducirá la cantidad de servicios que quedan abiertos. Estos son los puertos y protocolos mínimos:

+
[cols="15,10,55"]
|===
| Protocolos | Puertos | Propósito 


| TCP, UDP | 111 | Portmapper (se utiliza para negociar qué puertos se utilizan en las solicitudes de NFS) 


| TCP, UDP | 635 | NFS mountd (recibe solicitudes de montaje NFS) 


| TCP, UDP | 2049 | Tráfico de red NFS 


| TCP, UDP | 4045 | Network Lock Manager (NLM, lockd) - gestiona las solicitudes de bloqueo. 


| TCP, UDP | 4046 | Network Status Monitor (NSM, statd) - notifica a los clientes de NFS los reinicios del servidor para la gestión de bloqueos. 
|===
.. *Zona de disponibilidad*: selecciona la zona de disponibilidad y la subred.
+
Debes seleccionar la misma zona de disponibilidad en la que está implementado tu VMware SDDC si quieres evitar los costes derivados del tráfico entre zonas de disponibilidad.

.. *Cifrado*: al utilizar la opción *Advanced create*, puedes seleccionar el nombre de la clave de cifrado de AWS en el menú desplegable.
.. *Control de acceso a los almacenes de datos*: al usar la opción *Advanced create*, puedes seleccionar si todos los hosts pueden acceder a los almacenes de datos o si solo determinados nodos del clúster de vSphere en una subred específica pueden acceder a los almacenes de datos.


. En la sección «Detalles del sistema de archivos», introduce la siguiente información:
+
.. *Datos de acceso a ONTAP*: introduce y confirma la contraseña de ONTAP.
.. *Credenciales de la máquina virtual de almacenamiento* (solo en creación avanzada): introduce y confirma la contraseña de la máquina virtual de almacenamiento. La contraseña puede ser específica para este sistema de archivos, o bien puedes utilizar la misma contraseña que hayas introducido para las credenciales de ONTAP.


. En la sección *Resumen*, puedes consultar la configuración del sistema de archivos FSx for ONTAP y del almacén de datos que el asesor de migración de VMware ha diseñado en función de la información que has facilitado.
. Selecciona *Crear* para implementar el sistema de archivos FSx for ONTAP. Este proceso puede tardar hasta 2 horas.
+
Si quieres, en la ventana Codebox puedes seleccionar *Redirect to CloudFormation* para crear el sistema de archivos con una pila de CloudFormation.

+
En cualquier caso, puedes seguir el progreso de la creación en CloudFormation.



.Resultado
Se implementó el sistema de archivos FSx for ONTAP.
