---
sidebar: sidebar 
permalink: setup/links-overview.html 
keywords: links, accounts, connectivity, 
summary: Un enlace de Workload Factory establece una relación de confianza y conectividad entre una cuenta de Workload Factory y uno o varios sistemas de almacenamiento en la nube. 
---
= Conoce los enlaces de NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un enlace de NetApp Workload Factory crea una relación de confianza y conectividad entre una cuenta de Workload Factory y uno o varios sistemas de almacenamiento en la nube. Esto te permite supervisar y gestionar determinadas funciones del sistema de almacenamiento directamente mediante llamadas a la API de REST de ONTAP que no están disponibles a través de la API de tu proveedor de nube.

No necesitas un enlace para empezar a utilizar Workload Factory, pero en algunos casos tendrás que crear un enlace para desbloquear todas las funciones y capacidades de Workload Factory.



[[why-links-are-beneficial]]
== Por qué los enlaces son beneficiosos

Los enlaces son útiles porque permiten a Workload Factory realizar operaciones que no están disponibles de forma nativa a través de la API de tu proveedor de servicios en la nube. Los enlaces permiten funciones avanzadas de ONTAP y automatización, lo que mejora la gestión de tus sistemas de almacenamiento en la nube.

Estas son algunas de las ventajas de utilizar enlaces:

* El enlace permite que NetApp Console envíe comandos de ONTAP directamente a tu sistema de almacenamiento en la nube, lo que te ofrece funciones avanzadas de ONTAP que van más allá de lo que tu proveedor de la nube ofrece de forma nativa.
* Los enlaces aprovechan las funciones remotas sin servidor para ejecutar código en respuesta a eventos. Este enfoque sin servidor elimina la dependencia de una instancia en ejecución en tu VPC.




[[how-links-work]]
== Cómo funcionan los enlaces

Los enlaces aprovechan servicios remotos de computación sin servidor, como AWS Lambda y Oracle Cloud Infrastructure Functions. Estos servicios ejecutan código en respuesta a eventos y gestionan automáticamente los recursos informáticos que requiere ese código. Los enlaces que crees forman parte de tu cuenta de NetApp y están asociados con la cuenta correspondiente del proveedor de nube.

Después de crear un enlace, puedes asociarlo a uno o varios sistemas de almacenamiento en la nube. Cada sistema de almacenamiento en la nube solo puede asociarse a un enlace dentro de la misma cuenta de NetApp. Si tienes varias cuentas de NetApp, un mismo sistema de almacenamiento en la nube puede asociarse a enlaces adicionales en diferentes cuentas de NetApp.

Puedes crear y asociar enlaces desde la página Enlaces en NetApp Console para tus sistemas de almacenamiento en la nube.

Puedes autenticar enlaces utilizando las credenciales almacenadas en el servicio de credenciales de Workload Factory o con el servicio de credenciales de tu proveedor de nube. Workload Factory no admite cambiar los modos de autenticación.



[[costs]]
== Costes

Cada transacción que realiza el servicio de computación sin servidor de tu proveedor de servicios en la nube conlleva un coste. Como actúa como proxy entre los dos sistemas, tiene un coste cuando el servicio envía una solicitud a la API de REST de ONTAP en un sistema de archivos y cuando devuelve la respuesta a Workload Factory.

* link:https://aws.amazon.com/lambda/pricing/["Obtén más información sobre los costes relacionados con el uso de AWS Lambda"^]
* link:https://www.oracle.com/cloud/cloud-native/functions/["Más información sobre los costes relacionados con el uso de Oracle Cloud Infrastructure Functions"^]




[[when-a-link-is-required]]
== Cuando se necesita un enlace

Workload Factory necesita un enlace para mostrar cierta información y realizar algunas tareas. Si intentas realizar una operación que requiere un enlace y no has asociado ningún enlace con el sistema de almacenamiento en la nube, Workload Factory te avisará de que la operación requiere un enlace.

Las funciones que requieren un enlace incluyen:

* Estado de buena arquitectura de las configuraciones de sistemas de almacenamiento en la nube para el mantenimiento proactivo, la fiabilidad y la optimización de la relación entre coste y rendimiento
* Supervisión y alertas de eventos de ONTAP EMS
* NetApp Protección autónoma contra ransomware (ARP/IA)
* Observabilidad integral mejorada de la capacidad en todos los sistemas de almacenamiento en la nube
* Replicación de datos de volúmenes y máquinas virtuales de almacenamiento, gestión y supervisión
* Provisionamiento y gestión de recursos compartidos SMB/CIFS y de la política de exportación NFS
* Gestión de volúmenes iSCSI en un sistema de almacenamiento en la nube
* Creación y gestión de políticas de snapshot para un SLA de protección personalizado
* Mejoras en la gestión de inodos para la gestión automática de la capacidad
* Crecimiento automático de volúmenes para el escalado elástico
* Creación y gestión de clones, para la clonación de datos instantánea y en el lugar
* Mostrar métricas adicionales directamente desde tu sistema de almacenamiento en la nube, como la versión del sistema
* Visualización de los detalles de la VM de almacenamiento y del LIF del clúster, incluidas las funciones, los endpoints, los nodos, las direcciones IP y el estado
* Desglose por componentes de los eventos de latencia




[[related-information]]
== Información relacionada

Aprende a crear y asociar enlaces para:

* link:../fsx-storage/create-link.html["Amazon FSx for NetApp ONTAP"]
* link:../oci/create-link.html["OCI NetApp Storage Service"]

